### PR TITLE
fix app height

### PR DESCRIPTION
**Pull request by pjtatlow**
I still haven't been able to reproduce your whitespace issue, but this fixes another issue that I found and I'm hoping it helps? 

If it doesn't we may need to Zoom or something to figure it out.

### CODE REVIEW

**Comment by pjtatlow** [comment]
The only feature I know isn't there is when you highlight the code and only
that code gets run. I don't know if you remember me complaining about that
last year but I still find it a little confusing so I'm trying to figure
out how to tell the user that it's only running part of your code.

Other than that, I don't have anything else on my TODO list! I'm pretty
happy with how it is so far.

Is that feature a must have on your list?

**Comment by srp33** [comment]
I'm on the fence about keeping that feature. As you said, it probably
causes more confusion than it helps. I forget whether we've discussed this,
but an option to address this need in the future is to add some type of
debugging sandbox where they can test their code more thoroughly.

One thing I asked about (and I might have missed your response) is the
question marks in the test results. The question mark feels distracting to
me. What if we left it blank or made it some type of hyphen instead?

One other issue I'm seeing. If I submit a solution, and the solution
doesn't pass, it saves my code. But it doesn't show me which tests passed
or failed when I refresh the page. Can that be fixed?

**Comment by pjtatlow** [comment]
I like the idea of a debugging sandbox! We should talk about that in more
detail after we get this released maybe.

I actually got rid of the question marks, so it’s just blank now.

As far as the last one, remember that when the page loads it isn’t loading
the last submission anymore, it’s loading the presubmission code always. So
there aren’t necessarily test results to show always.

We could do something where if the presumbission code is exactly the same
as the last submission then we show those test results when the page loads?

But then if you make any changes and refresh, your test results will be
blank again, which might be confusing.

Thoughts?

**Comment by srp33** [comment]
I'm still trying to process this, but it seems that if they have submitted
(not just run), then when the page loads, we should always show the status
of the tests when they were last submitted, even if their code has changed
since then. I think it's okay if their code has changed since then. That
would be similar to if they submit, get the results back, and then edit
their code (without refreshing). Do you see an issue with that? If so,
let's jump on Zoom and chat through it.

**Comment by pjtatlow** [comment]
Happy to chat about it on Zoom. The situation I’m concerned with is what if
they submit and it fails, then they fix the code and it passes but they
didn’t submit? Then when they reload the page it shows all of their tests
failing.

**Pull request merged**
